[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.19.1" 

[context.production.environment]
  VITE_TURN_USERNAME = "studybuddy"
  VITE_TURN_PASSWORD = "your-secure-turn-password"
  VITE_TURN_SERVER = "turn.studybuddy.com" 